### ISSUE TITLE
Confusing "unable to open <crate>: File is a directory" error

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-assistant#117]
If `cargo-prusti` panics while verifying a crate, this IDE extension reports an error diagnostics that points to a folder. If the user clicks on that diagnostics, the IDE reports an "unable to open <crate>: File is a directory" error message, which might be confusing.

![image](https://user-images.githubusercontent.com/45197576/141795351-e5900e08-f91e-4d98-98d4-d6b8b038ae91.png)
(Thanks to @HKalbasi for raising this issue!)

This behavior is a trade-off. If Prusti crashes, we want to list a position-less error in the list of verification errors, but VSCode's API doesn't really allow that.

**Comment by HKalbasi** [comment]
Maybe using [`showErrorMessage`](https://code.visualstudio.com/api/references/vscode-api#window.showErrorMessage) is better than emitting a diagnostic item?

**Comment by fpoli** [comment]
I'm open to it, but the disadvantage of `showErrorMessage` is that it's meant to be disposed, after which it's unclear if a program with no diagnostics is a program that fully verified or a program that crashed Prusti. The two possible states have completely different meaning, which is what I don't like.

One alternative is to implement our own "list of verification error" tab. There might be some reusable component to do that.

**Comment by HKalbasi** [comment]
Isn't the label in the bottom navbar enough to distinguish between two state?
![image](https://user-images.githubusercontent.com/45197576/141826862-f27bc271-7a81-47ef-828d-af80de7f4fd5.png)

It can be set to "⚠️ prusti crashed"

**Comment by fpoli** [comment]
Good point! I forgot that we changed the extensions to only display the results of the latest verified file/crate. Given that, the status bar is enough. All the logic is in this method: https://github.com/viperproject/prusti-assistant/blob/56722a92cdd62555f64f24348b6d9516974aef2c/src/diagnostics.ts#L588-L661
