### ISSUE TITLE
Undefined number of warnings in the status bar

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-assistant#135]
When verifying the program
```rust
fn main() {}
```
the number of warnings reported in in the status bar is wrong:
```
Verification of fail 'program.rs' succeeded with undefined warnings.
                                                 ^^^^^^^^^
```
Expected message:
```
Verification of fail 'program.rs' succeeded with 1 warning.
```

**Comment by Aurel300** [comment]
Is this before or after 8c12156a2298fb99227c6a319998025577d79114 ?

**Comment by fpoli** [comment]
I'm using the published version. So, before. I didn't notice that commit. It should fix this issue, so I'll close.
