### ISSUE TITLE
Better error for missing Java in VSCode extension

### ISSUE THREAD

**Issue by Timmmm** [viperproject/prusti-assistant#204]
If you don't have Java installed the only sign is a message in the log window. It would be good if it gave an actual error message in the GUI.

**Comment by fpoli** [comment]
Thank you for the report. The extension is already supposed to report a user-friendly error message on activation if Java is missing: https://github.com/viperproject/prusti-assistant/blob/cc1085ccd212fcaa9ce305f7d1ac7135949d7f51/src/extension.ts#L30

Could you double check if that message has been reported? Could you also attach the log and possibly a screenshot that includes the status bar?

Anyway, in case the prerequisite checks fail the extension could report a permanent error message in Prusti's status bar. That would be an easy and useful enhancement.

**Comment by fpoli** [comment]
I can't reproduce this issue; the described error message should already be reported.
