### ISSUE TITLE
Prusti Assistant broken on MacOS

### ISSUE THREAD

**Issue by mabbamOG** [viperproject/prusti-assistant#25]
error description: for any of the VSCode Prusti commands, i get the error 

```
Command 'Prusti: [command]' resulted in an error [...]
(command '[extended command name]' not found)
```

os info: MacOS BigSur MBPro "13 2018, VSCode 1.52

**Comment by fpoli** [comment]
Thanks for the report! It seems that something is stopping the extension before the commands are registered. Could you attach the log messages of the extension (View → Output → Prusti Assistant Trace)?

I also noticed that all our CI jobs started failing this week. It might be related.

**Comment by fpoli** [comment]
Also, could you add your output of `java --version` to this issue?

**Comment by fpoli** [comment]
We just published a new version of the extension, which you can try.

**Comment by fpoli** [comment]
Is the issue still valid? Marking as `help wanted` as I just have remote access to one MacOS, on which the extension works fine.
