### ISSUE TITLE
Absolute error path reported as relative

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-assistant#252]
Prusti-Assistant doesn't handle absolute error paths correctly. An error on a file reported on an absolute path `/a/b/c` is rendered as if the path was `./a/b/c`.

The bug is probably on the following line. When joining, we should first check if `file_name` is alredy an absolute path.
https://github.com/viperproject/prusti-assistant/blob/e990a8868be796467f8c2ac74786d39528fd98c9/src/diagnostics.ts#L177

I noticed this while reproducing the issue in https://github.com/viperproject/prusti-dev/issues/1493.

**Comment by quinn-dougherty** [comment]
This, or something similar, blocks the usage of workspaces for me.

**Comment by fpoli** [comment]
> This, or something similar, blocks the usage of workspaces for me.

This issue should only affect the position where the errors are reported. It should not prevent Prusti from running. What do you observe?

**Comment by fpoli** [comment]
Thanks, so the issue is either this or https://github.com/viperproject/prusti-assistant/issues/218.
