### ISSUE TITLE
Malformed specification error for pre/post conditions. 

### ISSUE THREAD

**Issue by Lee-Janggun** [viperproject/prusti-assistant#38]
I am trying to get Prusti running on VSCode on a Mac. While following [this tutorial](https://viperproject.github.io/prusti-dev/user-guide/basic.html), the following code segment from it gave an error.

```rust

extern crate prusti_contracts;
use prusti_contracts::*;

#[ensures(result >= a && result >= b)]
#[ensures(result == a || result == b)]
fn max(a: i32, b: i32) -> i32 {
    if a > b {
        a
    } else {
        b
    }
}
```
The error message was as follows.
<img width="439" alt="스크린샷 2021-01-27 오전 4 27 37" src="https://user-images.githubusercontent.com/56512187/105894803-0445bd80-6058-11eb-8ca6-81ea4509980e.png">

I have updated Prusti with the `Prust: update dependencies` command, but the results were the same. Any possible fix?
Specs:
Hardware: MacBook Air (Retina, 13-inch, 2020), Intel Core i5
OS: Big Sur 11.1
Prusti: 0.5.5
Java: 15.0.1
Rustc: 1.49.0
Rustup: 1.23.1

**Comment by Aurel300** [comment]
Do you have Prusti Assistant switched to "Nightly"? See the warning in the [installation](https://viperproject.github.io/prusti-dev/user-guide/install.html) chapter.

**Comment by Lee-Janggun** [comment]
That was the problem. I misunderstood that having 0.5.5 will be fine. Thank you for your quick reply
