### ISSUE TITLE
Verification of crates

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-assistant#45]
Currently, the extension can only verify programs that can be compiled with a simple `rustc <program.rs>` call. So, just standalone Rust files with no Cargo dependencies. However, the code to support verification of crates from the extension is already there. The missing steps are:
- [ ] Add a VS Code command and a button to start the verification of a crate.
    - Regarding the button, it would be nice to replace the current "Verify with Prusti" button with something like a dropdown menu that lets to choose between "Verify standalone program with Prusti" and "Verify crate with Prusti".
 - [ ] Add tests that run the "verify crate" command on a collection of crates (including: empty crate, crate with dependencies, non-compiling crate).

**Comment by akhi3030** [comment]
Is there a rough ETA for when this might be available?  I am very excited to try it out on https://github.com/dfinity/ic.

**Comment by fpoli** [comment]
We don't have plans to add this soon to the IDE, however Prusti supports verification of crates from the command line. For that, please refer to the readme/guides of https://github.com/viperproject/prusti-dev. One of the binaries in the releases is `cargo-prusti`, which you run from the folder of the crate that you want to compile.

Be aware of https://github.com/viperproject/prusti-dev/issues/2. To work around that, you can use the [`extern_spec` annotations](https://viperproject.github.io/prusti-dev/user-guide/verify/external.html).

**Comment by fpoli** [comment]
If you really want to use an IDE, a completely untested way (credits to @vakaras for the idea) is to install the `rust-analyzer` plugin and change the settings such that it runs the `prusti` cargo sub-command instead of `check`. This requires you to manually install Prusti first on your system, such that its binaries are in the program path used by the IDE. I'm not sure what the failure scenarious might be. For sure, Prusti would be a bit slower because it would not use the Prusti server.

**Comment by akhi3030** [comment]
Thank you so much for the suggestions.  I'll experiment and get back with updates.

**Comment by fpoli** [comment]
Closed by #99
