### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by voidc** [viperproject/prusti-assistant#7]
I use VSCodium which uses the [open-vsx.org](https://open-vsx.org/) extension registry.
Currently prusti-assistant is only available in the Visual Studio Marketplace.
I propose additionally publishing the extension to open-vsx.org.
Maybe [this](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) guide helps.

**Comment by fpoli** [comment]
Thanks for pointing us to the open-vsx.org registry, I didn't know it. We'll consider it!

**Comment by Aurel300** [comment]
As I thought in the last meeting, this really should not be involved. We need to sign in with `viper-admin` into Open VSX, and [get an access token](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token). Then the publishing can actually be done [with identical packages](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token) to both registires.

**Comment by fpoli** [comment]
@Aurel300 I added the token to the repo's secrets.

**Comment by fpoli** [comment]
Should I do something to reserve a namespace? Like, `viper-admin` or `prusti`?

**Comment by Aurel300** [comment]
> Should I do something to claim a namespace? Like, `viper-admin`, `viperproject` or `prusti`?

Yes, I can't actually read the secret in the repo settings (only update it). The `publisher` field of our `package.json` field says `viper-admin`, and we already use that on the VSCode marketplace. According to the [guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-create-the-namespace), you should do:

```
$ npm install -g ovsx
$ npx ovsx create-namespace viper-admin -p <token>
```

**Comment by fpoli** [comment]
> > Should I do something to claim a namespace? Like, `viper-admin`, `viperproject` or `prusti`?
> 
> Yes, I can't actually read the secret in the repo settings (only update it). The `publisher` field of our `package.json` field says `viper-admin`, and we already use that on the VSCode marketplace. According to the [guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-create-the-namespace), you should do:
> 
> ```
> $ npm install -g ovsx
> $ npx ovsx create-namespace viper-admin -p <token>
> ```

Done:
> 🚀  Created namespace viper-admin
